# Dependencies

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Extract:
## Read COVID-19 CSV data into a dataframe

In [2]:
csv_file = "./Resources/conposcovidloc.csv"
covid_data_df = pd.read_csv(csv_file, parse_dates = ['Accurate_Episode_Date'])

# Transform:
## Drop unnecessary columns

In [3]:
covid_columns = ['Row_ID', 'Accurate_Episode_Date', 'Age_Group', 'Client_Gender', 'Case_AcquisitionInfo',
                'Outcome1', 'Reporting_PHU', 'Reporting_PHU_City', 'Reporting_PHU_Postal_Code', 'Reporting_PHU_Latitude',
                'Reporting_PHU_Longitude']

covid_transformed_data_df = covid_data_df[covid_columns].copy()
covid_transformed_data_df.head()

,Row_ID,Accurate_Episode_Date,Age_Group,Client_Gender,Case_AcquisitionInfo,Outcome1,Reporting_PHU,Reporting_PHU_City,Reporting_PHU_Postal_Code,Reporting_PHU_Latitude,Reporting_PHU_Longitude
0,1,2020-01-22,50s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358
1,2,2020-01-21,50s,MALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358
2,3,2020-01-24,20s,FEMALE,Travel-Related,Resolved,Middlesex-London Health Unit,London,N6A 5L7,42.981468,-81.254016
3,4,2020-02-05,20s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358
4,5,2020-02-16,60s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358

# Transform:
# Rename columns

In [4]:
covid_transformed_data_df = covid_transformed_data_df.rename(columns={'Row_ID': 'ID', 
                                'Accurate_Episode_Date': 'Date',
                                'Client_Gender': 'Gender',
                                'Case_AcquisitionInfo': 'Case_Source',
                                'Outcome1': 'Outcome',
                                'Reporting_PHU': 'Health_Unit',
                                'Reporting_PHU_City': 'City',
                                'Reporting_PHU_Postal_Code': 'Postal_Code',
                                'Reporting_PHU_Latitude': 'Latitude',
                                'Reporting_PHU_Longitude': 'Longitude'})

covid_transformed_data_df.head()

,ID,Date,Age_Group,Gender,Case_Source,Outcome,Health_Unit,City,Postal_Code,Latitude,Longitude
0,1,2020-01-22,50s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358
1,2,2020-01-21,50s,MALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358
2,3,2020-01-24,20s,FEMALE,Travel-Related,Resolved,Middlesex-London Health Unit,London,N6A 5L7,42.981468,-81.254016
3,4,2020-02-05,20s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358
4,5,2020-02-16,60s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,43.656591,-79.379358

# Transform:
## rounding numeric values (Lat and Long)

In [5]:
covid_transformed_data_df['Latitude'] = covid_transformed_data_df['Latitude'].round()
covid_transformed_data_df['Longitude'] = covid_transformed_data_df['Longitude'].round()

covid_transformed_data_df.head()

,ID,Date,Age_Group,Gender,Case_Source,Outcome,Health_Unit,City,Postal_Code,Latitude,Longitude
0,1,2020-01-22,50s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,44.0,-79.0
1,2,2020-01-21,50s,MALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,44.0,-79.0
2,3,2020-01-24,20s,FEMALE,Travel-Related,Resolved,Middlesex-London Health Unit,London,N6A 5L7,43.0,-81.0
3,4,2020-02-05,20s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,44.0,-79.0
4,5,2020-02-16,60s,FEMALE,Travel-Related,Resolved,Toronto Public Health,Toronto,M5B 1W2,44.0,-79.0

# Extract:
## Read second data source

In [6]:
csv_file = "./Resources/Ministry_of_Health_Service_Provider_Locations.csv"
health_data_df = pd.read_csv(csv_file)
health_data_df.head()

,X,Y,OGF_ID,MOH_SERVICE_PROVIDER_IDENT,SERVICE_TYPE,SERVICE_TYPE_DETAIL,ENGLISH_NAME,FRENCH_NAME,ENGLISH_NAME_ALT,FRENCH_NAME_ALT,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_DESCRIPTOR,COMMUNITY,POSTAL_CODE,GEOMETRY_UPDATE_DATETIME,EFFECTIVE_DATETIME,SYSTEM_DATETIME,OBJECTID
0,-79.369347,43.649813,127907976,9999999990,AIDS Bureau,CBAESP,2-Spirited People of the 1st Nations,NaN,NaN,NaN,145 Front Street East,Unit 105,Practice Location,Toronto,M5A1E3,NaN,2020-04-03T20:42:44.000Z,2020-04-03T20:42:44.000Z,753601
1,-79.384047,43.664337,127907977,9999999991,AIDS Bureau,CBAESP,Action Positive VIH-SIDA,NaN,NaN,NaN,543 Yonge Street,4th floor,Practice Location,Toronto,M4Y1Y5,NaN,2020-04-03T20:42:44.000Z,2020-04-03T20:42:44.000Z,753602
2,-79.377200,43.649990,127907978,9999999992,AIDS Bureau,CBAESP,African and Caribbean Council on HIV/AIDS in O...,NaN,NaN,NaN,20 Victoria Street,4th floor,Practice Location,Toronto,M5C2N8,NaN,2020-04-03T20:42:44.000Z,2020-04-03T20:42:44.000Z,753603
3,-79.364552,43.654664,127907979,9999999993,AIDS Bureau,CBAESP,Africans in Partnership Against AIDS,NaN,NaN,NaN,526 Richmond Street East,2nd Floor,Practice Location,Toronto,M5A1R3,NaN,2020-04-03T20:42:44.000Z,2020-04-03T20:42:44.000Z,753604
4,-79.375083,43.667650,127907980,9999999994,AIDS Bureau,CBAESP,AIDS Bereavement & Resiliency Project of Ontar...,NaN,NaN,NaN,490 Sherbourne Street,2nd Floor,Practice Location,Toronto,M4X1K9,NaN,2020-04-03T20:42:44.000Z,2020-04-03T20:42:44.000Z,753605

# Transform:
## Drop unnecessary columns

In [7]:
health_columns = ['X', 'Y', 'OGF_ID','SERVICE_TYPE', 'ENGLISH_NAME', 'COMMUNITY','POSTAL_CODE']

health_transformed_data_df = health_data_df[health_columns].copy()
health_transformed_data_df.head()

,X,Y,OGF_ID,SERVICE_TYPE,ENGLISH_NAME,COMMUNITY,POSTAL_CODE
0,-79.369347,43.649813,127907976,AIDS Bureau,2-Spirited People of the 1st Nations,Toronto,M5A1E3
1,-79.384047,43.664337,127907977,AIDS Bureau,Action Positive VIH-SIDA,Toronto,M4Y1Y5
2,-79.377200,43.649990,127907978,AIDS Bureau,African and Caribbean Council on HIV/AIDS in O...,Toronto,M5C2N8
3,-79.364552,43.654664,127907979,AIDS Bureau,Africans in Partnership Against AIDS,Toronto,M5A1R3
4,-79.375083,43.667650,127907980,AIDS Bureau,AIDS Bereavement & Resiliency Project of Ontar...,Toronto,M4X1K9

# Transform:
## Rename columns

In [8]:
health_transformed_data_df = health_transformed_data_df.rename(columns={'Y': 'Latitude', 
                                'X': 'Longitude',
                                'OGF_ID': 'Location_ID',
                                'SERVICE_TYPE':'Service_Type',
                                'ENGLISH_NAME': 'Name',
                                'COMMUNITY': 'Community',
                                'POSTAL_CODE': 'Postal_Code'})

health_transformed_data_df.head()

,Longitude,Latitude,Location_ID,Service_Type,Name,Community,Postal_Code
0,-79.369347,43.649813,127907976,AIDS Bureau,2-Spirited People of the 1st Nations,Toronto,M5A1E3
1,-79.384047,43.664337,127907977,AIDS Bureau,Action Positive VIH-SIDA,Toronto,M4Y1Y5
2,-79.377200,43.649990,127907978,AIDS Bureau,African and Caribbean Council on HIV/AIDS in O...,Toronto,M5C2N8
3,-79.364552,43.654664,127907979,AIDS Bureau,Africans in Partnership Against AIDS,Toronto,M5A1R3
4,-79.375083,43.667650,127907980,AIDS Bureau,AIDS Bereavement & Resiliency Project of Ontar...,Toronto,M4X1K9

# Transform:
## Drop unnecessary rows

In [10]:
service_types = ['Independent Health Facility', 'Retirement Home', 'Long-Term Care Home',
    'Senior Active Living Centre', 'Hospital - Corporation', 'AIDS Bureau',
    'Hospital - Site', 'Community Health Centre', 'Public Health Unit Office',
    "Children's Treatment Centre"]

health_columns = ['Latitude', 'Longitude', 'Location_ID','Service_Type', 'Name', 'Community','Postal_Code']

health_clean_data_df = pd.DataFrame(columns=health_columns)

for i in range(len(service_types)):
    temp = health_transformed_data_df.loc[health_transformed_data_df['Service_Type'] == service_types[i], :] 
    health_clean_data_df = health_clean_data_df.append(temp)
    
health_clean_data_df.head()

,Community,Latitude,Location_ID,Longitude,Name,Postal_Code,Service_Type
1898,Toronto,43.821204,127908432,-79.304566,Top Medical Imaging Inc.,M1V3S1,Independent Health Facility
1899,Toronto,43.761416,127908433,-79.410211,Hullmark Medical Digital Imaging,M2N0G3,Independent Health Facility
1900,Brampton,43.691960,127908434,-79.753156,Elite Diagnostics X-Ray & Ultrasound,L6W3X4,Independent Health Facility
1901,Toronto,43.660498,127908435,-79.386059,Metro Radiology (Bay & Gerrard),M5G1N8,Independent Health Facility
1902,Toronto,43.707863,127908436,-79.394156,Metro Radiology (Glencairn),M4P1E8,Independent Health Facility

# Transform:
## set index for dataframe and round lat and lng

In [18]:
health_clean_data_df.set_index("Location_ID", inplace=True)
health_clean_data_df['Latitude'] = health_clean_data_df['Latitude'].round()
health_clean_data_df['Longitude'] = health_clean_data_df['Longitude'].round()

health_clean_data_df.head()

,Community,Latitude,Longitude,Name,Postal_Code,Service_Type
Location_ID,,,,,,
127908432,Toronto,44.0,-79.0,Top Medical Imaging Inc.,M1V3S1,Independent Health Facility
127908433,Toronto,44.0,-79.0,Hullmark Medical Digital Imaging,M2N0G3,Independent Health Facility
127908434,Brampton,44.0,-80.0,Elite Diagnostics X-Ray & Ultrasound,L6W3X4,Independent Health Facility
127908435,Toronto,44.0,-79.0,Metro Radiology (Bay & Gerrard),M5G1N8,Independent Health Facility
127908436,Toronto,44.0,-79.0,Metro Radiology (Glencairn),M4P1E8,Independent Health Facility

# Load:
## Create database connection

In [19]:
connection_string = "postgres:postgres@localhost:5432/COVID19_DB"
engine = create_engine(f'postgresql://{connection_string}')

covid_transformed_data_df.to_sql(name='covid_cases', con=engine, if_exists='replace', index=False)
health_clean_data_df.to_sql(name='health_service_providers', con=engine, if_exists='replace', index=False)